version: 2
registries:
  npm-registry-npm-pkg-github-com-forward3d:
    type: npm-registry
    url: https://npm.pkg.github.com/forward3d
    token: ${{secrets.GH_PACKAGES_TOKEN}}

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  target-branch: dep/new
  registries:
  - npm-registry-npm-pkg-github-com-forward3d
